### PR TITLE
Fix border Radius

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@vkedwardli I tried your PR and it works great. Would it be the same if we set the borderWidth to 0 directly right?

**Comment by vkedwardli** [comment]
Yes it works with 0 borderWidth, but speaking of zero value I just noticed that it won't work if we don't provide a value in the first place, https://github.com/vkedwardli/react-native-expo-image-cache/commit/b8fe5eea8826e7377c75db8b58645f94de4ca73c should can fix the undefined problem

**Comment by vkedwardli** [comment]
Please check the latest commits in my branch, not sure if that's the way you prefer to fix the lint error
https://github.com/vkedwardli/react-native-expo-image-cache/commits/fix-border-radius

**Comment by wcandillon** [comment]
@vkedwardli perfect!

**Comment by wcandillon** [comment]
@vkedwardli Thks a lot for this contribution and for your help 🙋🏼‍♂️

**Pull request merged**
