### PR TITLE
Support require('path') usage

### PR DESCRIPTION
**Pull request by vkedwardli**
In case the same Image component need to display local image by `require` originally, and setting `preview` + `uri` afterwards

### CODE REVIEW

**Comment by wcandillon** [comment]
@vkedwardli Why would you use this component for a local image?

**Comment by vkedwardli** [comment]
So I don't have to `import { Image as RNImage } from "react-native", and due to my application state, the same Image view sometimes need to display a local image when there is no `uri` available (the `uri` information is fetch from the server afterwards)

**Comment by wcandillon** [comment]
Wouldn't be better to use defaultSource from https://facebook.github.io/react-native/docs/image.html?

**Comment by vkedwardli** [comment]
Oh? Is it supported on Android now? I thought `defaultSource` is only supported on iOS

**Comment by wcandillon** [comment]
Shouldn't `preview` support local images as parameter and then make the URI parameter optional?

**Comment by vkedwardli** [comment]
In my environment I need to use `require` instead of the `file://` uri, so I use it like this.

Since I'm quite new to js / react native, so I'm not sure how to use `require('path')` inside the `{ uri: preview }`

**Comment by Piropa** [comment]
ON this, I wish to use a preloaded asset as preview image in a photo list, however the "preview" only accepts an uri. It would be nice to use the already loaded (via reaquiere('path')) asset instead.

**Comment by wcandillon** [comment]
@Piropa This use case make sense, overall this component is not symmetric enough yet with <Image>, I need to look into it.

**Comment by vkedwardli** [comment]
@Piropa require('path') and uri string are both supported in this way now

**Comment by wcandillon** [comment]
@vkedwardli I like where this is going. Where is `ImageSourcePropTypes` imported from? It feels weird that the final image would be a local resource, should we really allow this? 🤔I'm not convinced. But for the preview, it definitely makes sense. Let me know your thoughts and I will help to get this merged.

**Comment by vkedwardli** [comment]
`ImageSourcePropType` is from here: https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageSourcePropType.js

Actually the final image component can only created by the `uri` string (if you don't get the image from the internet, there is no point to use this library and caching), but for the `preview` or the `defaultSource`, user can provide the original `uri` string (no changes to original usage), or a complete `ImageSourcePropType`, or just the local require (which the type is `Int`)

**Comment by wcandillon** [comment]
I like it. Why isn't https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageSourcePropType.js imported in your PR?

**Comment by vkedwardli** [comment]
@wcandillon sorry I'm not quite sure how to import it, please see my latest commit and see if I do it correctly

```
const ImageSourcePropType = PropTypes.oneOfType([
  ImageURISourcePropType,
  // Opaque type returned by require('./image.jpg')
  PropTypes.number,
  // Multiple sources
  PropTypes.arrayOf(ImageURISourcePropType),
]);
```
Since it includes `PropTypes.number`, I have removed the `number` type also

**Comment by wcandillon** [comment]
@vkedwardli Thanks for your work, I'm currently looking to integrate this. What is the goal of defaultSource?

For preview, I would like to make the breaking change that it doesn't accept a string anymore but only `ImageSourcePropType` so people will manually have to update to `{ uri: "data..." }`

**Comment by vkedwardli** [comment]
The goal for `defaultSource` is for providing an option to user (like me), to be able to use the same component only for local "required" image without any animation/transition, and then when the state changes (the presence of `preview` base64 string and `uri` string as fetched from server later), it can change the local image to the preview and then let this component to do the fetching + animation

Example:
When you are talking to someone in Telegram, which the target's profile picture is null, currently Telegram will generate the profile picture using name's prefix

Prefix

But when the user added the profile picture later, the app will receive the `preview` base64 string + `uri` string, and after the image is downloaded, the original transition can happen

**Comment by wcandillon** [comment]
Thks for sharing your use case with me 👍🏻

**Pull request merged**
