### PR TITLE
Add blur effect for Android also

### PR DESCRIPTION
**Pull request by vkedwardli**
Using Facebook's Fresco IterativeBoxBlurPostProcessor to blur the preview image, CPU intensive but acceptable for small base64 image, doesn't have the same remove blur animation as iOS but it looks much better now

### CODE REVIEW

**Comment by wcandillon** [comment]
@vkedwardli 🤯

**Comment by wcandillon** [comment]
@vkedwardli Just tried it and I like it. What are your thoughts on using on iOS as well? And replace <BlurView> with a simple opacity mask like for Android? I will try on it on iOS.

**Comment by wcandillon** [comment]
@vkedwardli Also tried different values below 1 for Android and I'm getting good result with 0.5. Not much better but there is a tiny bit more definition on some images for this value.

**Comment by vkedwardli** [comment]
It is a different story on iOS, since your original implementation was animating the blur intensity using pure GPU calculation.
However for Android there is no true Blur View, if we need to animate the blur intensity, we need to generate lots of blur image with different `blurRadius`, so your approach on iOS still wins 😎

**Comment by vkedwardli** [comment]
The values is really personal taste, FYR I'm using `85` for the blur intensity instead of `100` 🤪

**Comment by wcandillon** [comment]
@vkedwardli Regarding the iOS implementation, I did some testing and you are right. Honestly 85 sounds :) I'd be willing to but it in the main branch.

**Pull request merged**
