### PR TITLE
Fix bug with transparent images

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by LouisJS** [comment]
Does that fix works for you ? It doesn't for me.
`"react-native-expo-image-cache": "^1.2.2",`

**Comment by LouisJS** [comment]
Btw. I'm using react-native-expo-image-cache's `Image` component inside a `PureComponent` to get better performance with my `FlatList`. (above 50+ items).

Could it cause conflict with the way the `Image` component works ? 🤔

**Comment by wcandillon** [comment]
@LouisJS This is so strange, I checked the content of the package of the package and it seems to be there. Can you check with the latest version? 🤔Sorry for the trouble.

**Comment by LouisJS** [comment]
It is working with `react-native-expo-image-cache@2.0.0 `. Somehow it wasn't in `1.2.2` ?

Anyway. It does work. The backgroundColor in Image is taken in account with transparent background and Image are loading normally.

Thanks for the quick update ! 💯

**Pull request merged**
