### PR TITLE
Added props for more customisation

### PR DESCRIPTION
**Pull request by dimoFeeld**
Added props for blur tint and transition duration.

### CODE REVIEW

**Comment by radiodario** [comment]
👍

**Comment by wcandillon** [comment]
@dimoFeeld isn't the `tint` attribute `tintColor`? If yes, is `dark`? a proper default value? 🤔

**Comment by dimoFeeld** [comment]
@wcandillon I got the props from here https://docs.expo.io/versions/latest/sdk/blur-view

**Comment by wcandillon** [comment]
Thanks a lot for clarifying, will be available in a few minutes in 3.1.1

**Pull request merged**
