### PR TITLE
Preview resize mode

### LINKED ISSUE #59: `preview` not resize with require('image/path')
Thanks for this awesome library!

When I try `preview` with the local image face the following issue, image fetch with `uri` seems ok:
screen shot 2018-04-08 at 8 42 18 pm

Version: 2.0.2

```
        if (images && images[0]) {
            return <Image resizeMode={'stretch'} style={{ height: 100, width: 100 }} {...{ uri: images[0].imgUrl }} />;
        } else {
            return (
                <Image
                    resizeMode={'stretch'}
                    style={{ height: 100, width: 100 }}
                    {...{ preview: require('../../assets/images/mini.jpg') }}
                />
            );
        }
```

### PR DESCRIPTION
**Pull request by brendan-jefferis**
Fixes #59

### CODE REVIEW

**Comment by cowai** [comment]
@wcandillon This too.

**Comment by wcandillon** [comment]
Can you fix the conflict? I will merge this 👍🏻

**Comment by brendan-jefferis** [comment]
> Can you fix the conflict? I will merge this 👍🏻

Done 👍

**Comment by wcandillon** [comment]
Thks!

**Pull request merged**
