### PR TITLE
Add render property

### LINKED ISSUE #41: Add cache support to components without replacing the Image element
Hi, 

I'm new to Github so I really don't know yet how to open a branch or pull a request, so I'm posting this idea/contribution here.

Well, as many, I use 3rd party components for my app, and many of those are built around the image component. So in order to make them work with this react-native-expo-image-cache I either have two options:

Option 1: I fork all the 3rd part components I use and replace the image object with this image object.

Option 2: I create a function to make the CacheManager support those components without forking them.

So, being the second option more apealing, I came up with this little function, which should allow me to use the CacheManager within 3rd party components:

```
// Returns the cached uri for an image, otherwise the fallback uri and triggers cache operation
// stateUri     : set as Control state var where to store the cached uri for the image.
// uri          : the original URI to be/already cached
// fallbackUri  : the URI to return while not yet cached
// listener     : listener that receives the cached URI when obtained and sets stateUri

function uriCache(stateUri: string, uri: string, fallbackUri: string, listener: Listener): string {
  if ((typeof stateUri === 'string') && stateUri)
    return stateUri
  else {
    CacheManager.cache(uri, listener)
  }
  return fallbackUri
}
```

Usage.....
Let's say I'll use the avatar component from the reac-native-elements library, and wish to cache the picture:
```

const profileUri = 'https://somewhereInTheWeb/somePic.jpg'
const defaultUri = 'https://somewhereInTheWeb/default.jpg'

class MyView extends React.Component {
  state = {
    cachedUri = undefined
  }
  render = () => (
    <Avatar source = {{
         uri: uriCache( state.cachedUri, profileUri, defaultUri,
                        uri => this.setState({cachedUri: uri}) )
       }}
    />
  }
}
```

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #41

### CODE REVIEW

**Comment by wcandillon** [comment]
@Piropa Can you test this PR to see if it fits you're use case?

@vkedwardli This PR would make an API breaking change, removing defaultSource in favor of `    renderDefault?: StyleObj => React.Node` Is that something that makes sense for you?

**Comment by vkedwardli** [comment]
@wcandillon If the users provide their own component exactly like the example:

`<Image style={{ height: 100, width: 100 }} render={(source, style, isPreview) => <RNImage {...{style, source}} />} />`

Does it mean the `blurRadius` trick is gone? (unless they include it themselves in the first place)

**Comment by wcandillon** [comment]
correct, what do you think?

**Comment by vkedwardli** [comment]
If the usage for `isPreview` is mainly for the `blurRadius`, I would prefer we just pass all the props which is `(imageProps)`, instead of `(source, style, isPreview)`, so while rendering the preview image comp, we can include the `blurRadius` in `imageProps`, without forcing the end user to handle the preview logic

For example, if user need to replace it with [react-native-elements's Avatar](https://react-native-training.github.io/react-native-elements/docs/avatar.html),

PROP | TYPE | DESCRIPTION
--- | --- | ---
source | object (image) | image source
avatarStyle | object (style) | style for avatar image
imageProps | object (ImageProperties) | optional properties to pass to the avatar e.g "resizeMode"

they can just use the `const {source, style, ...otherProps} = imageProps`, then
```
source = {source}
avatarStyle = {style}
imageProps = {otherProps}
```
This should work for both preview and final image component


Though I can't think of the actual usage for `isPreview` now, we can pass `(imageProps, isPreview)` for keeping the flexibility

**Comment by wcandillon** [comment]
@vkedwardli yes that makes sense 👍🏻

**Comment by wcandillon** [comment]
@vkedwardli I like your idea. Or what about make it a separate component if you don't want to use `<Image>` from React Native? Maybe it will keep things simpler?

**Comment by vkedwardli** [comment]
@wcandillon I thought that all image views are based on `<Image>` from RN?

**Comment by wcandillon** [comment]
@vkedwardli The goal of this PR is to enable people to use a custom component instead. I introduced a similar API for React Web at https://github.com/wcandillon/react-progressive-image-loading where maybe the image is used in a `` or as a background url in a div or something else.

**Comment by vkedwardli** [comment]
```
import {Image} from "react-native-expo-image-cache";
import {Avatar} from "react-native-elements";

<Image style={{ height: 100, width: 100 }} render={(imageProps, isPreview) => { 
    const {source, style, ...otherProps} = imageProps;
    return <Avatar
        small
        rounded
        source={source}
        avatarStyle = {style}
        imageProps = {otherProps}
        onPress={() => console.log("Works!")}
        activeOpacity={0.7}
    />
}} />

```

I'm not sure if I get your concern correctly, this is what I was proposing originally, you can see I'm passing the custom component `Avatar` (based on RN's `Image`) for the actual rendering

**Pull request closed without merging**
