### PR TITLE
Allow preview to be passed as uri string or object

### LINKED ISSUE #69: Warning: Failed prop type: Invalid prop `source` supplied to `Image`.
Hi, this repo is really a great improvement for Expo Images.
But this warning raised recently.

```
<CacheImage
        preview={getAvatarPlaceholder}
        uri={data.creator.photoURL}
        style={styles.userPic}/>

export const getAvatarPlaceholder = () => {
    return require('../assets/images/avatar-placeholder.png');
};


Warning: Failed prop type: Invalid prop `source` supplied to `Image`.
    in Image (at Image.js:92)
    in Image (at DiscoverScreen.js:347)
```

In output, it states that the error happens in Image.js:92 which is about preview.

### PR DESCRIPTION
**Pull request by brendan-jefferis**
Fixes #69

### CODE REVIEW

**Comment by cowai** [comment]
@wcandillon This would be great to have.

**Comment by scytherswings** [comment]
Is this good to go?

**Comment by wcandillon** [comment]
The use case is to load a non static image? shouldn't preview be always coming from `require()`?

**Comment by brendan-jefferis** [comment]
> The use case is to load a non static image? shouldn't preview be always coming from `require()`?

Yeah, the use case is to load a non-static image. Or I guess just specifying with `uri` rather than a `require`.

It's supported in the underlying [RN Image component](https://facebook.github.io/react-native/docs/image.html), so it seems reasonable for this lib to follow suit, your call though.

**Comment by wcandillon** [comment]
@brendan-jefferis I agree that if we were to accept this PR, I would make the preview property type symmetric with `source`. However, I am not seeing a compelling use case to use a non-static image in preview since the goal is to have a preview that can be displayed immediately.

**Comment by brendan-jefferis** [comment]
@wcandillon yes, you're right that a preview should by definition be a local file, imported via `require`. I made the mistake of just loading a tiny version of the image from the same database, defeating the entire purpose of a preview 😄 

I suspect the others in #69 may be doing something similar...

So then this PR should not be merged (since that was its sole purpose) and maybe the original issue should be updated with a quick note to users that previews shouldn't be referenced by external urls?

**Comment by wcandillon** [comment]
@brendan-jefferis I found a use case where it makes sense: inlined data url. For instance: 

```json
    "food": {
        "uri": "https://firebasestorage.googleapis.com/v0/b/react-native-e.appspot.com/o/b47b03a1e22e3f1fd884b5252de1e64a06a14126.png?alt=media&token=d636c423-3d94-440f-90c1-57c4de921641",
        "preview": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAECAYAAABGM/VAAAAAAXNSR0IArs4c6QAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsTAAALEwEAmpwYAAABWWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgpMwidZAAAAX0lEQVQIHQFUAKv/AUQxNf/9/gcA5fP8ACsXGwDt9esABO348QAWKQYAOh4aAPr0AgAR4BQABPj//QAbGwwALS8XAAX8EADH7uwAAvLzBQAV+SoAIv8zAB3+JgDrAfoAaw4fL0szIPEAAAAASUVORK5CYII="
    }
```

I will make a separate PR for this. Thks!

**Comment by wcandillon** [comment]
@brendan-jefferis Right now `preview` is symmetric to `source` in RNImage. Why would we want to make the `preview` type signature non-symmetric?

**Comment by brendan-jefferis** [comment]
> @brendan-jefferis Right now `preview` is symmetric to `source` in RNImage. Why would we want to make the `preview` type signature non-symmetric?

I think you're right, that `preview` should be the same as RNImage `source`, sorry if I was unclear. The data url example is definitely a valid use case.

**Comment by wcandillon** [comment]
@brendan-jefferis haha no worries, sorry I was confused since I didn't contribute to this module in a while. Thank you so much for contributing, really appreciate it 🙌🏻

**Pull request closed without merging**
