### PR TITLE
Improve cleanup on unmount

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@alanlanglois Thank you for your support. I'm currently testing this version in two of my project, wanna take a look too?

**Comment by alanlanglois** [comment]
@wcandillon I got this error, 

Unable to resolve mobx" from ".[projectpath]\node_modules\\react-native-expo-image-cache\\dist\\src\\Image.js"

**Comment by wcandillon** [comment]
😱 indeed
will publish a fix for it now
this is so bad 🤦‍♂️
need to add automatic releases to this project

**Comment by wcandillon** [comment]
Should be fixed now in 1.0.6

**Pull request merged**
